name: Unit Testing

on:
  pull_request:
    branches:
      - test

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Unit Tests
      run: pytest testCases.py 
          
    - name: Merge to Master (if tests pass)
      if: success()
      run: |
        git fetch origin
        git checkout main
        git merge ${{ github.event.pull_request.head.ref }}
        git push origin main
