name: Unit Testing

on:
  pull_request:
    branches:
      - test

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Install dependencies
      run: pip install -r requirements.txt
